apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mssql
  namespace: default
spec:
  selector:
    matchLabels:
      app: mssql
  serviceName: mssql
  replicas: 1
  template:
    metadata:
      labels:
        app: mssql
    spec:
      containers:
      - name: mssql
        image: simulation-db:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 1433
          name: tds
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: MSSQL_PID
          value: "Developer" # "Express"
        - name: MSSQL_SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: SA_PASSWORD
        # -------------------------------------------
        - name: DB_NAME
          value: "MyDb"
        - name: BAK_FILE
          value: "mydb.bak"
        - name: RESTORE_IF_ABSENT
          value: "1"
        # -------------------------------------------
        volumeMounts:
        - name: mssqldata
          mountPath: /var/opt/mssql
        # -------------------------------------------
        - name: mssqlbackup                         
          mountPath: /var/opt/mssql/backup
        # -------------------------------------------
        readinessProbe:
          tcpSocket:
            port: 1433
          initialDelaySeconds: 20
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 1433
          initialDelaySeconds: 40
          periodSeconds: 10
      volumes:
      - name: mssqlbackup
        persistentVolumeClaim:
          claimName: mssql-bak-pvc
  volumeClaimTemplates:
  - metadata:
      name: mssqldata
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 8Gi