apiVersion: v1
kind: PersistentVolume
metadata:
  name: mssql-bak-pv
spec:
  capacity:
    storage: 2Gi
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: manual
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/hostbackup
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-bak-pvc
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 2Gi
  storageClassName: manual
  volumeName: mssql-bak-pv